version: '3.8'
services:
  collector:
    build: ./collector
    volumes:
      - ./data:/workspace/data
    command: ["bash","-c","python3 /workspace/collect_sample_certs.py"]

  parser:
    build: ./parser
    volumes:
      - ./data:/workspace/data
      - ./results:/workspace/results
    depends_on:
      - collector
    command: ["bash","-c","python3 /workspace/parse_certs.py"]

  generator:
    build: ./generator
    volumes:
      - ./data:/workspace/data
      - ./results:/workspace/results
    depends_on:
      - parser
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    command: ["bash","-c","python3 /workspace/generate_and_create.py"]

  test-openssl:
    build: ./tests
    volumes:
      - ./results:/workspace/results
      - ./data:/workspace/data
    depends_on:
      - generator
    command: ["bash","-c","python3 /workspace/run_tests.py"]

